### ISSUE TITLE
Сохранение DFM как текста

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3057]
Originally reported on Google Code with ID 3057

```
Сейчас мы пытаемся перекодировать из двоичного объекта, если его имя "DFM" или является
РУИД-ом в строковом представлении.

Под это правило не попадают такие объекты:

    Properties: 
      Class: 'TgdcStorageValue'
      RUID: 147123543_1439110857
      AlwaysOverwrite: True
      DontRemove: False
      IncludeSiblings: False
    Fields: 
      PARENT: 154996723_1440956890 '\DFM\Tgdc_dlgAttrUserDefined'
      NAME: 'USR$WG_BANKSETTINGS'
      DATA_TYPE: 'B'
      STR_DATA: ~
      INT_DATA: ~
      DATETIME_DATA: ~
      CURR_DATA: ~
      BLOB_DATA: !!binary > 

Здесь имя элемента хранилища -- имя таблицы.


```

Reported by `gs1994` on 2013-03-13 13:23:31
