### ISSUE TITLE
Невозможно в коде создать платежное поручение

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin#3596]
Originally reported on Google Code with ID 3596

```
Вот такой код:

  dim SubType ' платежное поручение
  SubType = "147002243_15581101"

  set gdcDocument = Creator.GetObject(Application, "TgdcUserDocument", "")
  set dsDocument = Creator.GetObject(Application, "TDataSource", "")
  set gdcDocumentLine = Creator.GetObject(Application, "TgdcUserDocumentLine", "")

  gdcDocument.Transaction = Sender.OwnerForm.gdcObject.Transaction
  gdcDocument.SubType = SubType
  gdcDocumentLine.Transaction = Sender.OwnerForm.gdcObject.Transaction
  gdcDocumentLine.SubType = SubType
  gdcDocumentLine.SubSet = "ByParent"
  dsDocument.DataSet = gdcDocument
  gdcDocumentLine.MasterField = "id"
  gdcDocumentLine.DetailField = "parent"
  gdcDocumentLine.MasterSource = dsDocument

Вылетает на строке
gdcDocumentLine.SubType = SubType
(заметьте, gdcDocument.SubType = SubType проходит без проблем). Возможно, это связано
с наследованием?

Проверить можно, если в окне редактирования выписки выбрать в лукапе "Документы в выписку"
тип "платежное поручение" и нажать на звездочку справа. Обратите внимание, если там
же выбрать "Объявление на взнос наличными", то всё работает.
```

Reported by `alexandra.gsoftware` on 2015-05-26 13:40:36

**Comment by gsbelarus** [comment]
```
Смотреть на бд коплексной автоматизации.

Код исправлять в ветке /trunk
```

Reported by `gs1994` on 2015-05-26 13:44:24
- **Labels added**: Priority-Critical
- **Labels removed**: Priority-High

**Comment by gsbelarus** [comment]
```
При обновлении ЗП через пакет (там уже стоит ПИ по ЗПиОК) возникает вот такая ошибка


Поиск объекта по потенциальному ключу:
SELECT id FROM gd_documenttype WHERE ruid = :ruid
RUID: 147019384_119619099
16:47:55  Изменяется объект: Развитие научного работника, 147019384_119619099, gd_documenttype
[Ошибка] 16:47:55  Unknown class name/subtype TgdcUserDocumentLine 147019384_119619099

Причем на базе есть такой руид
```

Reported by `roberto1813` on 2015-05-26 13:54:27

**Comment by gsbelarus** [comment]
```
Стоп!

Это ошибка в настройках, а не в ядре Гедымина. Документы могуцт быть сложными шапка-Позиция,
а могут быть простыми, как, например, платежка. В первом случае есть TgdcUserDocument
с подтипом и TgdcUserDocumentLine с таким же подтипом. Во втором случае есть только
TgdcUserDocument. TgdcUserDocumentLine НЕТ.

В старом Гедымине есть ошибка, он позволял создавать позицию там, где ее быть не может.
Например для платежки. Нерадивый разработчик этим пользовался. 

Новый Гедымин кинет ошибку.

Что сейчас делать? Исправить настройки.
```

Reported by `gs1994` on 2015-05-26 14:03:59

**Comment by gsbelarus** [comment]
```
А что с ошибкой в ЗП?
Документ Развитие научного работника не имеет позиций
```

Reported by `alexandra.gsoftware` on 2015-05-26 14:10:25

**Comment by gsbelarus** [comment]
```
Так откуда тогда TgdcUserDocumentLine ?? Где вообще кидается ошибка?
```

Reported by `gs1994` on 2015-05-26 14:12:17

**Comment by gsbelarus** [comment]
```
При обновлении ПИ
```

Reported by `roberto1813` on 2015-05-26 14:13:36

**Comment by gsbelarus** [comment]
```
Надо посмотреть. если в тексте ПИ есть TgdcUserDocumentLine с таким подтипом, то это
ошибка, которая просочилась через старый экзешник. Тогда подправить на эталоне, пересохранить
и загрузить.
```

Reported by `gs1994` on 2015-05-26 14:18:16

**Comment by gsbelarus** [comment]
```
Берем новейший экзешник.

По хорошему код рассматриваемого макроса надо переписать потому что там смешались в
кучу кони и люди. Быстрое и грязное решение проверять gdcDocumentLine.CheckSubType(...).
Вернет True -- есть такой подтип и можно присваивать. Нет -- значит нет.

С ЗП разбираться отдельно. Почему там такой объект попал в ПИ. и в ПИ ли он попал или
это что-то другое кидает ошибку.
```

Reported by `gs1994` on 2015-05-26 14:20:30
- **Status changed**: `Fixed`

**Comment by gsbelarus** [comment]
```
по зп: так выглядит этот объект в файле (ОК - метаданные)
    Properties: 
      Class: "TgdcUserDocumentType"
      RUID: 147019384_119619099
      AlwaysOverwrite: False
      DontRemove: False
      IncludeSiblings: False
    Fields: 
      ADDNUMBER: ~
      MASK: ~
      FIXLENGTH: ~
      PARENT: "147020857_119619099 Документы Зарплаты и ОК\\Документы OK"
      NAME: "Развитие научного работника"
      DESCRIPTION: ~
      CLASSNAME: "TgdcUserDocumentType"
      DOCUMENTTYPE: "D"
      OPTIONS: ~
      HEADERRELKEY: "147019390_119619099 Развитие научного работника, USR$WG_SCIENCEDEVELOP"
      LINERELKEY: ~
      DISABLED: 0
      RUID: "147019384_119619099"
      BRANCHKEY: "147019398_119619099 Исследователь\\Зарплата и Отдел кадров\\Отдел
кадров\\Сотрудники\\Личная карточка\\Развитие научного работника"
      REPORTGROUPKEY: "147019397_119619099 Отдел кадров\\Развитие научного работника"
      ISCOMMON: 0
      ISCHECKNUMBER: 0
      HEADERFUNCTIONKEY: ~
      HEADERFUNCTIONTEMPLATE: ~
      LINEFUNCTIONKEY: ~
      LINEFUNCTIONTEMPLATE: ~
      EDITIONDATE: 2000-01-01T00:00:00+03:00
```

Reported by `alexandra.gsoftware` on 2015-05-26 14:24:39
